name: Tests avec différentes versions de Python

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.9, 3.8, 3.7]

    runs-on: ubuntu-latest

    steps:
    - name: Utiliser Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Vérifier la version de Python
      run: python --version
      
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installer Django
      run: |
        pip install django
        
    - name: Exécuter le script Python
      run: python manage.py
